### ISSUE TITLE
backup scheduling

### ISSUE THREAD

**Issue by tidebre67** [thunderbird/import-export-tools-ng#677]
@cleidigh , Christopher, 

IETNG 14.1.4
it looks that in ´folder name for backup´ the customize tick box does not work.
In the backup folder always the folder name and date is stored. 
Due to that the possibility to choose ´just files modified after last backup´ does not work as it should.

@tidebre67

**Comment by cleidigh** [comment]
@tidebre67 
Odd as I fixed an error with the folder names to address that issue and did back and forth testing... Will check both issues. 
Thanks 
Christopher

**Comment by cleidigh** [comment]
@tidebre67 
I can't reproduce your error or another user error with setting the count.
I added debug that may help : 
- #681 

Christopher

**Comment by tidebre67** [comment]
@cleidigh  :

Christopher, regret, still no change. that's strange.

first backup:

Folder name for backup: 

customized:  xxxx.default-release

save: always all files

backup content: all profile files

number of backups to retain:  all

Result after backup:  xxxx.default-release-20250122-0855

(should be xxxx.default-release)

--------------------------------------

second backup:

folder name for backup:

customised:   xxxx.default-release

save: just files modified after last backup

backup content: all profile files

number of backups to retain: all

result after backup:  xxxx.default-release-2250122-0912


the first backup still exists.

that means no complete single backup file after backups.


Thomas

**Comment by tidebre67** [comment]
@cleidigh 

Christopher, pls inform your test email address, cannot recall. Will send the backup.log as i cannot comment on this. Or should i use your private email address ?

i got the differential on the second but i expected the differentials will be incorporated into the first complete backup.

**Comment by cleidigh** [comment]
@tidebre67 
You can always use my private email, it's safer since my test email can get erased sometimes.

The differential backup folder will only be the files that changed since the last backup date. The weakness of the new number of backups to retain is that it doesn't know about the backup types. So it would delete a full backup if it was old enough. So if you are deleting older backups then they really all need to be full backups. A fuller more Useful method would involve saving full backups before deleting old ones. This would be a decent amount of work which with all the other work is something that would have to wait for a long time.

I don't think you have to send me anything since it's doing what it should. And that behavior has not changed. Do you think the date in the customized name is bad?

**Comment by tidebre67** [comment]
@cleidigh 
as far as the date is concerned it is not bad, but i cannot see any difference to ´automatic´ setting.

on the other hand the new method confuses me.
i understood that the differential backups only files changed data after the last backup.
But how to keep one COMPLETE profile in the backup folder ? (or have i do select always the ´always all files´ tick box ?)
But this backup will always take long time.

in previous ietng version the differentials were build in into the origional profile in the backup folder and therefore it was equal to the TB profile stored in APPData/roaming folder. in case of a crash there was a complete profile backup file available.

if i am completely wrong kindly enlighten me.
@tidebre67

**Comment by cleidigh** [comment]
@tidebre67 
I would have to check,but I have not touched backups until now so I don't see how that could change. What I didn't realize is some people used the custom name as unchanging and overwote the old baxkup. I'm going to revert that. I still don't understand your naming issue.

For the differential, can you reproduce the old behavior in v14.1.2?
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
14.1.2  works as i expected.
i tested 14.1.3-b9 as well , even this works as in the past.
@tidebre67

**Comment by cleidigh** [comment]
@tidebre67 
I don't get it. The custom name should not affect this.
Can you send me the two backup logs and tell me how you got them.
Christopher

**Comment by cleidigh** [comment]
@tidebre67 
in b5 I restored the naming.
https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.5/xpi/beta/import-export-tools-ng-14.1.5-b5-tb.xpi
Christopher

**Comment by tidebre67** [comment]
@cleidigh 
i think you got it. 
14.1.5-b5 works like in earlier versions.
settings: 
folder name for backups: customized
Save: always all files (first run)  - just files modified after last backup  (second run)
backup content: all profile files (first and second run)
number of backups to retain: 1

after second run there is one complete profile in the backup folder containing data from first and second run.

will send you some pics by seperate mail.
@tidebre67

**Comment by cleidigh** [comment]
@tidebre67 
Thanks! I finally understand, sorry for my density.
The second run (using an UNCHANGING CUSTOM NAME) just overwrites the changed files and the result, as you said, the result is the single folder contains a full, latest backup. I think I had started a backup before shutting down last night and this morning I saw the dialog with what looked like completion, but the dialog remained. Then I stupidly did not record the error I saw in the log. Arrg!!!

It was a path error and now I'm paranoid because I can't screw up this fix. 

If you can try permutations and see if you observe that, that would be very helpful.
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
>If you can try permutations and see if you observe that, that would be very helpful.<

can give me a clue what i have to do to assist in this respect ?

@tidebre67

**Comment by cleidigh** [comment]
@tidebre67 
I guess just do various backup types and see if the dialog ever fails to close.
Then look at the console for errors.
@cleidigh

**Comment by Sergio3N** [comment]
> [@tidebre67](https://github.com/tidebre67) in b5 I restored the naming. https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.5/xpi/beta/import-export-tools-ng-14.1.5-b5-tb.xpi Christopher

This solve my problem. Thanks!

**Comment by DrStrange** [comment]
Hi @cleidigh ,
b5 doesn't seem to do this for me.
So if I understand what @tidebre67 (and I) want, is to first do a full backup, then set subsequent backups to just files changed since last backup and with number of backups set to 1, then there would only be one backup folder.
Well, I have b6 installed. Before I installed it, I uninstalled IETNG, deleted all the IETNG prefs in about:config and restarted TB.
With frequency set as 1 day, folder name is automatic, save always all files, number of backups to retain is 1:
I did a full backup, then set save to Just files modified after last backup:
With each backup thereafter that is run, the modified files are saved into a separate folder. The result that I would expect is that the modified files are saved into the folder containing the full backup, with the result that there is only ever one backup folder created.
Is that not what should happen?
The actual result is that there is a new folder being created on every backup.

Also, when a backup is started, the progress indicator windows opens and you click ok to start the backup. However, when the progress reaches 100%, it does not close automatically. You then have to close it by clicking cancel.

**Comment by cleidigh** [comment]
@DrStrange 
Your observation is correct. However, to obtain what you want you need to use the custom name. With this name there is no date or suffix, therefore the same folder name remains unchanged. The differential backups go into this folder.

I'm working on the dialog issue, but only saw it once and have not reproduced since so I'm on the hunt. Will post progress here.
Thanks far your patience.
@cleidigh

**Comment by DrStrange** [comment]
My own opinion about the customised folder name and not saving the date and time anymore, is that I would prefer the date and time to be also saved. I don't really understand your comments on this:
"I did change the custom name to include the date and index thinking all backup folders Should have the date. Perhaps this was a bad choice. Ideally I would make the name fully customizable."
and 
"What I didn't realize is some people used the custom name as unchanging and overwote the old baxkup. I'm going to revert that."
Surely as the date and name were being saved then the custom name does change on every backup because the date and time are being changed. 
If people set number of backups to more than one, then the backups won't be overwritten. If they do set backups to only one, that is on them.

Thank you.

**Comment by cleidigh** [comment]
@DrStrange 
I think the bottom line is this, if you use the custom, unchanging name, there is always only one backup and the number of backups to retain is not relevant.
@cleidigh

**Comment by cleidigh** [comment]
@DrStrange 
Thanks that gives me Something to compare.
@cleidigh

**Comment by Sergio3N** [comment]
> Also, when a backup is started, the progress indicator windows opens and you click ok to start the backup. However, when the progress reaches 100%, it does not close automatically. You then have to close it by clicking cancel.

I confirm, in b6 the progress reaches 100% but it does not close the windows

However, b6 performs backups correctly without renaming the folder if it is set as a custom name

**Comment by cleidigh** [comment]
@DrStrange 
@Sergio3N 
@tidebre67 
Right now I am wrestling with a critical issue with mbox import so I have to get that stable before returning to this.
@Sergio3N if you can capture your debug console output when the dialog freezes that would be helpful. Also what backup setup caused this and does it happen every time?
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
the dialog issue is not critical. therefore no hurry.
@tidebre67

**Comment by cleidigh** [comment]
@tidebre67 
@DrStrange 
@Sergio3N 
Ok i fixed my dumb error with the dialog in b8
- #681 
- @cleidigh

**Comment by DrStrange** [comment]
@cleidigh 
Thanks for this. I can confirm the backup dialog window now closes automatically when the backup is completed using b8.
I ran another backup with the error console open under b6 and I think I captured more relevant info. This time I opened the error console before running the backup. 

![Image](https://github.com/user-attachments/assets/05cabade-6570-4262-8591-6f9ea64482bb)

**Comment by cleidigh** [comment]
@DrStrange 
Perfect!
Yes that's the error %-)

@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 

>Ok i fixed my dumb error with the dialog in b8<

also confirm dialog window closes automatically.

will close this issue.

@tidebre67
