### ISSUE TITLE
v14.1.7 Various issues

### ISSUE THREAD

**Issue by chrisjj** [thunderbird/import-export-tools-ng#731]
Hi. Please see 4 and 5 as a priority. Thanks.

Windows 7 with UK locale (time zone UK, current time GMT), TB 115.10.0, extension from [file ](https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.7/xpi/beta/import-export-tools-ng-14.1.7-b1-tb.xpi),  Version 4.0.44 Last Updated 23 March 2025.

1) This version's Details has the same version number as the previous, whereas a higher number is expected.

2) This version's Details has a Last Updated date that is before the time of the last update showing on github - 16 hours ago.

3) On Export Messages As > mbox File > New mbox File, if the file already exists, the operation silently fails to update it.

4 ) On Export Messages As > Message Index > HTML Format and CSV Format output, date e.g. 2007-29-7 21:47 is in a non-international format rather than the international YYYY-MM-DD format expected, and has month number not padded, whereas padded to two places is expected.

5) On Export Messages As > Message Index > HTML Format and CSV Format date output, the time (and hence possibly date) can be incorrect - with a variable amount. Example #1 Received message having `Date: Sun, 29 Jul 2007 22:47:26 +0200` gets `21:47` whereas `20:47` is expected. Example #2 Received message having `Date: Thu, 26 Jun 2008 13:22:57 +0100` gets `13:22` whereas `12:22` is expected. Example #3 Sent message `Date: Sun, 19 Mar 2006 13:32:56 +0000` gets `13:32` as expected.

6) On Export Messages As > Message Index > HTML Format and CSV Format give a directory/folder select dialog box whereas a file save dialog box is expected.

7) The options dialog box's Filenames tab's Customized format for filenames group implies it applies to all filenames, whereas and indication it applies to message file filenames only is expected.

Thanks for a great add-on!

**Comment by cleidigh** [comment]
@chrisjj 
I am having a bad eye day and I program by eye gaze so I will be brief.
You are testing beta so 1 & 2 are not updated by atn.
3 I can fix for release 
4 what do you mean about "output date"

bear in mind I'm using a date library and I may not be able to address these for the important hotfix release 
I will try if my eyes behave ;-}
@cleidigh

**Comment by chrisjj** [comment]
> 4 what do you mean about "output date"

"output, date"

I have expanded it to clarify.

> bear in mind I'm using a date library and I may not be able to address these for the important hotfix release

I think the fact the EML file dates are correct suggest making the index dates should by easy.

Thanks.

**Comment by cleidigh** [comment]
I'm still not understanding output date. The os file date?

**Comment by chrisjj** [comment]
No it is the date in the output (HTML/CSV).

**Comment by cleidigh** [comment]
The message date in each line of the index?
sorry there are so many dates

**Comment by cleidigh** [comment]
screenshot?

**Comment by chrisjj** [comment]
> The message date in each line of the index?

Yes.

**Comment by chrisjj** [comment]
> screenshot?

Message source:

![Image](https://github.com/user-attachments/assets/bb593651-a0fd-4c70-b60c-06964d8665f4)


HTML index:
![Image](https://github.com/user-attachments/assets/31bb0a23-ab51-48e3-b6a0-632ebde583c8)

**Comment by cleidigh** [comment]
got it 
thats configured on the misc tab

**Comment by chrisjj** [comment]
Thanks! I had `%Y-%d-%n %H:%M` and I am now changing to `%Y-%m-%d %H:%M`.

The result of HTML index is:

![Image](https://github.com/user-attachments/assets/67455cca-272b-44bf-81ec-ce38d9ff9bcd)

And the same if I revert the change.

**Comment by cleidigh** [comment]
ok thats probably a tb115 vs v128 error will lookm

**Comment by cleidigh** [comment]
@chrisjj 
FYI I just found out 240k users have been updated to v14.1.6. I thought I had stopped it around 30k.
This means it's imperative I release Monday.
I will try to address most of your issues, butprobably not all.
@cleidigh

**Comment by chrisjj** [comment]
> I will try to address most of your issues, but probably not all. I have to avoid rat holes that would delay the release. I hope that is understandable.

Totally! Thanks. I'd be happy for just fixes to the index incorrect times and the errors.

By the way, this beta has broken both mbox format commands too:

![Image](https://github.com/user-attachments/assets/cacb3b94-26c1-47ca-aca9-ed60920fd078)

**Comment by cleidigh** [comment]
@chrisjj 
Stated that way it's basically everything...
I don't know about 4, after two stable years that may be a rat hole, but I will look at it after the other bugs.
@cleidigh

**Comment by cleidigh** [comment]
@chrisjj 
I could not reproduce your error. You were still testing b1.
I'm strongly considering not supporting v115 with v14.1.7.
It may have been an error to do so.
We are going into the weekend and I don't suspect you will be available for testing.
I have b3, try it and capture the debug console.
Worst case Ipatch v14.1.5

https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.7/xpi/beta/import-export-tools-ng-14.1.7-b3-tb.xpi

@cleidigh

**Comment by DenB10** [comment]
@cleidigh 

Just to let you know: I'm using version 1.4.1.7-b2 with TB 115 on Win7 and it works fine for me. However, issue #3 reported by @chrisjj is true (with TB 128 and 136 too).

P.S.
Just a word of advice: Don't be too demanding on your health, get some rest...

@DenB10

**Comment by chrisjj** [comment]
> Stated that way it's basically everything...

Sorry to be unclear. By "the errors" I meant the fatal errors reported by TB in dialog boxes titled Error.

**Comment by cleidigh** [comment]
@DenB10 
I'm starting to pull my hair out.
I get a Save As popup if I try to overwrite an mbox in v115 or v128???
What is going on.
I'm seriously considering dropping v115 since this update adds nothing to v115.
But you see this issue on v128??
@cleidigh

**Comment by chrisjj** [comment]
> I'm strongly considering not supporting v115 with v14.1.7.

It is still worth fixing the fatal fails with some version I hope, since otherwise Windows 7 users are dumped.

> We are going into the weekend and I don't suspect you will be available for testing.

I will.

> I have b3, try it 

All four commands succeed. Thanks!

**Comment by cleidigh** [comment]
@chrisjj 
@DenB10 
Ok good that b3 removed errors, will have to check which change fixed later.
# 3 still not getting. I get the save dialog, use existing mbox name then get Save As confirm popup asking if I want to overwrite, both 115 or 128

@cleidigh

**Comment by chrisjj** [comment]
> # 3 still not getting.

On b3, I too am now now getting the problem.

>  I get the save dialog, use existing mbox name then get Save As confirm popup asking if I want to overwrite, both 115 or 128

![Image](https://github.com/user-attachments/assets/6c9cbe6b-d74a-44b5-8b37-c34a0484e013)

**Comment by cleidigh** [comment]
@chrisjj 
Ok then we are seeing the correct behavior. Will see what @DenB10 reports on his v115 and v128 with b3

I think it may be module caching.
@cleidigh

**Comment by cleidigh** [comment]
@chrisjj 
ok while @DenB10 checks b3
try b4 and also after first try, restart tb and try again.
https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.7/xpi/beta/import-export-tools-ng-14.1.7-b4-tb.xpi
@cleidigh

**Comment by chrisjj** [comment]
On b4, no change i.e. all four commands work, and #3 fixed. Same after restart. Thanks.

**Comment by cleidigh** [comment]
@chrisjj 
good. I rechecked on v128
If @DenB10 double confirms, then I will cleanup and see if I can peek at # 4
I'm leary of that.
@cleidigh

**Comment by DenB10** [comment]
@cleidigh 

Sorry for the late reply, my vm crashed...

I've tested b3 and b4 with Betterbird 115 and Betterbird 128 and I get the same problem: if I ask for the mbox file to be replaced in the confirmation dialog (which I've always had even in previous betas), the replacement doesn't happen.

@DenB10

**Comment by cleidigh** [comment]
@DenB10 
Ok I was missing it, I see it now.
@chrisjj  Do you still see the overwrite problem we do?
@cleidigh

**Comment by DenB10** [comment]
@cleidigh 

>Ok I was missing it, I see it now.

Is it reasonable to see this now? I think the fix can wait.

@DenB10

**Comment by cleidigh** [comment]
@DenB10 
@chrisjj 
Yeah, this is intertwined with append, it's old spaghetti code.
Going to let it go.
I have to release before v137 comes out. Already checked and v14.1.7 breaks due to at least one depreciation...I can't deal with that.

I will do t the index name and I'm done.
Will need spot checks before release Sunday night.
Axel should be able to review Monday 
@cleidigh

**Comment by chrisjj** [comment]
> [@chrisjj](https://github.com/chrisjj) I just saw you edited first post and marked # 4 as solved? 

Yes. It is solved by me changing the Option > Misc config as you suggested, to the value now shown in the report. I would myself say the undesirable initial state is itself an issue, and that might rate as a bug. Clearly only you can fix that. But the fact there's a user workaround puts it low priority, I think.

> So for # 6 the index has always been default index.html. That's an easy fix if we have got everything else in order.

I'm not a believer in "always been" :) but if you're saying that Working as Designed, fine - since now is probably not the right time for mere improvements :)

**Comment by cleidigh** [comment]
As I said I I can do the index name.
I wont touch the overwrite

**Comment by chrisjj** [comment]
>Do you still see the overwrite problem we do?

I see `New mbox File` to existing filename:

![Image](https://github.com/user-attachments/assets/0a34c131-2800-46c9-9573-bc2b10d1d25c)

gives the desired dialog:

![Image](https://github.com/user-attachments/assets/378a53dd-9a24-41b3-9fc6-3f4b5540a49c)

_**but**_ then silently fails to write to the file.

**Comment by cleidigh** [comment]
yes.
I'm not touching that one, see above

**Comment by cleidigh** [comment]
I will post b5 with index name later

**Comment by cleidigh** [comment]
@chrisjj 
@DenB10 
After experiments I again found the code expects just a folder . I can't mess with the structure as stupid as that sounds. I have to get moving to my rewrite.
Sorry.
@cleidigh

**Comment by chrisjj** [comment]
Understood. No problem.

Do you think you'll be able to fix #5, the wrong dates in EML filenames? That's quite a serious one, with no workaround. Thanks.

**Comment by chrisjj** [comment]
PS I'll check every couple of hours over the weekend for any test request.

**Comment by cleidigh** [comment]
@chrisjj 
# 5 is dates in the index files which you solved by having the correct format.
There is nothing about EML files which like all message filenames uses the custom date format on tab 2. So you can use the same format you like with the indexes.
@cleidigh

**Comment by cleidigh** [comment]
Didn't mean to "shout",dont know why gh changed font

**Comment by chrisjj** [comment]
> # 5 is dates in the index files which you solved by having the correct format.

Sorry, now I find I was wrong to say SOLVED. It is only partially solved. I shall update the report.

> There is nothing about EML files 

It affects EML files equally. Apologies for being unclear.

**Comment by cleidigh** [comment]
@chrisjj 
whatever you did for index will work for filenames 

b5 release candidate 
release tomorrow 
https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.7/xpi/beta/import-export-tools-ng-14.1.7-b5-tb.xpi
@cleidigh

**Comment by chrisjj** [comment]
> [@chrisjj](https://github.com/chrisjj) whatever you did for index will work for filenames

What I did for index was simply change the format string and no it did not work for index or filenames on b4. The b4 problem is independent of format.

b4 is messing up the time value in Example 1.

**Comment by cleidigh** [comment]
Have to release,

**Comment by cleidigh** [comment]
For the PrintingTools update next week that uses the same lib, I can look at this and see about a resolution.

**Comment by chrisjj** [comment]
> b5 release candidate release tomorrow https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.7/xpi/beta/import-export-tools-ng-14.1.7-b5-tb.xpi [@cleidigh](https://github.com/cleidigh)

Thanks. This has b3's failure of date in index, CSV and filename as b4.

I suggest the release notes document this bug, noting it can cause data loss and has no known workaround.

Upon release, I'll submit it here as a separate issue to aid users.

Thanks.

**Comment by chrisjj** [comment]
> This has b3's failure of date in index, CSV and filename as b4.

I have a hunch that the cause is the code using file property ItemDate, which for EML files does _not_ return the Date: value, even returning the most recent Received date-time value!

**Comment by chrisjj** [comment]
PS Is the add-on attempting conversion to local time?

**Comment by cleidigh** [comment]
@chrisjj 
@DenB10 
Yes of course it's localized.
I think that is your error. Taking the js Intl.DateTimeFormat( as gold standard, see the following from the console.

``` 

d = new Date("Sun, 29 Jul 2007 22:47:26 +0200")
Date Sun Jul 29 2007 16:47:26 GMT-0400 (Eastern Daylight Time)

console.log(
  new Intl.DateTimeFormat("en-GB", {
    dateStyle: "full",
    timeStyle: "long",
    timeZone: "Europe/London",
  }).format(d),
);
Sunday, 29 July 2007 at 21:47:26 BST debugger eval code:1:9

```

So no date problems.
@cleidigh

**Comment by chrisjj** [comment]
> [@chrisjj](https://github.com/chrisjj) [@DenB10](https://github.com/DenB10) Yes of course it's localized. 

> So no date problems.

This is a problem - to any user needing archive EMLs named with an objective representation of the date i.e. from the message, independent of the machine doing the archiving.

The current behaviour causes mismatch of archives of the same EMLs made from machine differing in timezone.
